<?php
$this->load->view('layout/header');
?>



<!--contannt section-->
<app-about-us _nghost-c14="" class="ng-star-inserted">
   <div _ngcontent-c14="">
      <section _ngcontent-c14="" class="sbPageTopSec servicesPgSec">
         <div _ngcontent-c14="" class="container">
            <h2 _ngcontent-c14="">Privacy Policy</h2>
         </div>
      </section>
      <section _ngcontent-c14="" class="aboutSec">
         <div _ngcontent-c14="" class="container">
            <div _ngcontent-c14="" class="abtTxt">
               <p _ngcontent-c14="" style="    white-space: pre-line;"> 
Privacy Policy
Data Protection Policy (Part A.) and User Consent (Part B.)

Regarding the Use of Style Treat Studio App
A. Information on Data Protection
Style Treat Studio App,
https://styletreatstudio.com/

is operating the internet platform Style Treat Studio App (“Style Treat Studio App”). Style Treat Studio App. connects aspiring and professional models with photographers, agents and model agencies.
Style Treat Studio App is dedicated to a sensitive and reasonable use of personal data of the users of its services (“User(s)”). Certain personal User data is collected in the registration process.
With this privacy policy, Style Treat Studio App would like to inform its Users about its way of processing and using personal data in connection with its services.
1.Style Treat Studio App will respect applicable data protection laws.
2.Style Treat Studio App will only collect, process and use personal data in connection with its services and will not provide third parties with such data unless the User has provided his/her consent or Style Treat Studio App is permitted by law or obligated to do so in order to comply with any legal obligation.
3.When registering on Style Treat Studio App, either as a model or photographer/scout or as an agency the User is required to provide certain information and data.
4.Style Treat Studio App contains links to websites of third parties and cannot influence the way such third parties are collecting, processing and using personal data of visitors to these sites. Therefore, Style Treat Studio App declines any responsibility and liability for such third parties’ acts.
5.Style Treat Studio App is dedicated to the protection of the personal data of its Users and has therefore taken appropriate measures for the protection of this data. However, Style Treat Studio App declines any responsibility and liability for the disclosure of User data caused by defective data transfers and/or illegal access by third parties.
6.Style Treat Studio App collects only the domain name, but not the e-mail address of visitors to its Web page, the e-mail addresses of those who post messages to the bulletin board, the e-mail addresses of those who communicate with us via e-mail, the e-mail addresses of those who make postings to our chat areas, aggregate information on what pages consumers access or visit, User-specific information on what pages consumers access or visit, information volunteered by the user, such as survey information and/or site registrations, name and address, telephone number, fax number.
7.Style Treat Studio App is using “Google Analytics”, a service for analyzing purposes by Google Inc. (“Google”). Google Analytics uses “cookies”, i.e. text files that are stored on the computer of the User allowing the analysis of his/her use of Style Treat Studio App. The information generated by the cookie (including your IP address) is transferred to a Google server in the USA and stored there. Google will use this information to analyze your use of Style Treat Studio App, to compile reports on the web site activities on Style Treat Studio App and for the provision of other services in connection with the use of Style Treat Studio App and the Internet. Google may transfer such information to third parties if so prescribed by law or if third parties are processing them on behalf of Google. Google will not connect the IP addresses of Style Treat Studio App’s Users with other Google data. The User may prevent the installation of the cookies by setting his/her browser software accordingly, which may, however, reduce the usability of Style Treat Studio App by the User. By using Style Treat Studio App, the User declares his/her consent with the processing of his/her data by Google as described herein.
8.The User may, at any time, request information on his/her data actually stored by Style Treat Studio App by contacting Style Treat Studio App at support@styletreatstudio.com.
B. Declaration of Consent
When accepting this data protection policy during the process of registration on Style Treat Studio App, the User declares his/her consent to the use of his/her personal data as described below. This consent may be revoked any time in writing by sending a mail to support@styletreatstudio.com.
or via e-mail to support@styletreatstudio.com. The User acknowledges the information on data protection set out in part A. above and additionally declares his/her consent to the following:
1.Use of Personal Model Data by Authorized Photographers, Scouts and Agents
I agree that authorized photographers, scouts and agents who use Style Treat Studio App have access to the following personal data: profile name, age, gender, general location, personal statistics (measurements, descriptive details, preferred modeling disciplines, etc.), images and videos. If an authorized photographer, agent or scout is interested in you, you will be contacted through Style Treat Studio App’s website. If you choose to respond, information you voluntarily provide will be made available to the authorized scout or agent, otherwise, no personal identifying information will be disclosed.
You may also voluntarily wish to display other personal information in your profile. This can be changed at any time by logging in and choosing update profile to edit how and which information is displayed.
2.Use of Data by Co-operation Partners I agree that my personal data may also be used in the context of co-operations with partners and customers of Style Treat Studio App for purposes of market research and the improvement and customization of Style Treat Studio App’s services. In this context, my personal data may also be transferred to such partners and customers.
3.Cookies and Log-Files
I agree that Style Treat Studio App uses cookies as follows:
Style Treat Studio App uses cookies to store visitors’ preferences, record session information, record user-specific information on what pages users access or visit, record past activity at a site in order to provide better service when visitors return to our site, customize Web page content based on visitors' browser type or other information that the visitor sends.
Cookies are text files that are either temporarily stored in the random access memory or on the hard drive of your computer. They generally serve for offering the User the services of Style Treat Studio App with the User’s personal settings in each new session. Cookies are partly stored permanently on the User’s hard drive. The User may prevent this by setting his/her browser accordingly.
4.I agree that my personal data will be processed by Google as described in Part A Section 7 above.               
               </p>
            </div>
         </div>
      </section>
      
   </div>
</app-about-us>
<!--end of contant section-->



<?php
$this->load->view('layout/footer');
?>